version: '3'
services:
  backend:
    build: ./monitoring-backend
    ports:
      - "8080:8080"
  frontend:
    build: ./monitoring-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
